/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type Footer = {
  _id: string;
  _type: "footer";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  partner?: string;
  partnerLogos?: Array<{
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "logo";
    _key: string;
  }>;
  netzwerk?: string;
  netzwerkLogos?: Array<{
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "logo";
    _key: string;
  }>;
};

export type ImpressumSeite = {
  _id: string;
  _type: "impressumSeite";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seitentitelMenue?: string;
  menuReihenfolge?: number;
  slug?: Slug;
  angabenText?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  impressumText?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type KontaktSeite = {
  _id: string;
  _type: "kontaktSeite";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seitentitelMenue?: string;
  menuReihenfolge?: number;
  slug?: Slug;
  text?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  ueberschriftAnsprechpersonen?: string;
  textAnsprechpersonen?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type Netzwerkkarte = {
  _id: string;
  _type: "netzwerkkarte";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  ueberschrift?: string;
  text?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  standorte?: Array<{
    titel?: string;
    latitude?: number;
    longitude?: number;
    _type: "standort";
    _key: string;
  }>;
};

export type Auswirkungen = {
  _id: string;
  _type: "auswirkungen";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  ueberschrift?: string;
  grafik?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
};

export type Zugangswege = {
  _id: string;
  _type: "zugangswege";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  ueberschrift?: string;
  grafik?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
};

export type Projektbeschreibung = {
  _id: string;
  _type: "projektbeschreibung";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  ueberschrift?: string;
  text?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  zusatzinfos?: {
    grafik?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    };
    text?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }>;
  };
  teilprojekte?: {
    ueberschrift?: string;
    projekte?: Array<{
      ueberschrift?: string;
      text?: Array<{
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }>;
      grafik?: {
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        _type: "image";
      };
      _type: "teilprojekt";
      _key: string;
    }>;
  };
};

export type Vision = {
  _id: string;
  _type: "vision";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  ueberschrift?: string;
  text?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type Einleitung = {
  _id: string;
  _type: "einleitung";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  ueberschrift?: string;
};

export type HomeSeite = {
  _id: string;
  _type: "homeSeite";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seitentitelMenue?: string;
  menuReihenfolge?: number;
  slug?: Slug;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type AllSanitySchemaTypes = Footer | ImpressumSeite | KontaktSeite | Netzwerkkarte | Auswirkungen | Zugangswege | Projektbeschreibung | Vision | Einleitung | HomeSeite | SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityImageHotspot | SanityImageCrop | SanityFileAsset | SanityImageAsset | SanityImageMetadata | Geopoint | Slug | SanityAssetSourceData;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: ./sanity/lib/queries.ts
// Variable: NAVIGATION_QUERY
// Query: *[_type in ["homeSeite", "kontaktSeite", "impressumSeite"]] {seitentitelMenue, slug, menuReihenfolge  }
export type NAVIGATION_QUERYResult = Array<{
  seitentitelMenue: string | null;
  slug: Slug | null;
  menuReihenfolge: number | null;
}>;
// Variable: HOME_QUERY
// Query: *[_type == "homeSeite"][0]{  seitentitelMenue, slug}
export type HOME_QUERYResult = {
  seitentitelMenue: string | null;
  slug: Slug | null;
} | null;
// Variable: EINLEITUNG_QUERY
// Query: *[_type == "einleitung"][0]{  ueberschrift}
export type EINLEITUNG_QUERYResult = {
  ueberschrift: string | null;
} | null;
// Variable: VISION_QUERY
// Query: *[_type == "vision"][0]{  ueberschrift, text}
export type VISION_QUERYResult = {
  ueberschrift: string | null;
  text: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
} | null;
// Variable: PROJEKTBESCHREIBUNG_QUERY
// Query: *[_type == "projektbeschreibung"][0]{  ueberschrift,  text,  grafik{    asset->{_id, url},    alt  },  zusatzinfos{    grafik{      asset->{_id, url},      alt    },    text  },  teilprojekte{    ueberschrift,    projekte[]{      ueberschrift,      text,      grafik{        asset->{_id, url},        alt      }    }  }}
export type PROJEKTBESCHREIBUNG_QUERYResult = {
  ueberschrift: string | null;
  text: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  grafik: null;
  zusatzinfos: {
    grafik: {
      asset: {
        _id: string;
        url: string | null;
      } | null;
      alt: string | null;
    } | null;
    text: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }> | null;
  } | null;
  teilprojekte: {
    ueberschrift: string | null;
    projekte: Array<{
      ueberschrift: string | null;
      text: Array<{
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }> | null;
      grafik: {
        asset: {
          _id: string;
          url: string | null;
        } | null;
        alt: string | null;
      } | null;
    }> | null;
  } | null;
} | null;
// Variable: ZUGANGSWEGE_QUERY
// Query: *[_type == "zugangswege"][0]{  ueberschrift,  grafik{    asset->{      _id,      url    },    alt  }}
export type ZUGANGSWEGE_QUERYResult = {
  ueberschrift: string | null;
  grafik: {
    asset: {
      _id: string;
      url: string | null;
    } | null;
    alt: string | null;
  } | null;
} | null;
// Variable: AUSWIRKUNGEN_QUERY
// Query: *[_type == "auswirkungen"][0]{  ueberschrift,  grafik{    asset->{      _id,      url    },    alt  }}
export type AUSWIRKUNGEN_QUERYResult = {
  ueberschrift: string | null;
  grafik: {
    asset: {
      _id: string;
      url: string | null;
    } | null;
    alt: string | null;
  } | null;
} | null;
// Variable: NETZWERKKARTE_QUERY
// Query: *[_type == "netzwerkkarte"][0]{  ueberschrift,  text,  standorte[]{    titel,    latitude,    longitude  }}
export type NETZWERKKARTE_QUERYResult = {
  ueberschrift: string | null;
  text: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  standorte: Array<{
    titel: string | null;
    latitude: number | null;
    longitude: number | null;
  }> | null;
} | null;
// Variable: KONTAKT_SEITE_QUERY
// Query: *[_type == "kontaktSeite"][0]{ seitentitelMenue, text, ueberschriftAnsprechpersonen, textAnsprechpersonen}
export type KONTAKT_SEITE_QUERYResult = {
  seitentitelMenue: string | null;
  text: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  ueberschriftAnsprechpersonen: string | null;
  textAnsprechpersonen: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
} | null;
// Variable: IMPRESSUM_SEITE_QUERY
// Query: *[_type == "impressumSeite"][0]{ seitentitelMenue, angabenText, impressumText,}
export type IMPRESSUM_SEITE_QUERYResult = {
  seitentitelMenue: string | null;
  angabenText: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  impressumText: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
} | null;
// Variable: FOOTER_QUERY
// Query: *[_type == "footer"][0]{  partner,  netzwerk,  partnerLogos[]{    asset->{_id, url},    alt,    name,    url  },  netzwerkLogos[]{    asset->{_id, url},    alt,    name,    url  }}
export type FOOTER_QUERYResult = {
  partner: string | null;
  netzwerk: string | null;
  partnerLogos: Array<{
    asset: {
      _id: string;
      url: string | null;
    } | null;
    alt: string | null;
    name: null;
    url: null;
  }> | null;
  netzwerkLogos: Array<{
    asset: {
      _id: string;
      url: string | null;
    } | null;
    alt: string | null;
    name: null;
    url: null;
  }> | null;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    "\n  *[_type in [\"homeSeite\", \"kontaktSeite\", \"impressumSeite\"]] {seitentitelMenue, slug, menuReihenfolge\n  }\n": NAVIGATION_QUERYResult;
    "*[_type == \"homeSeite\"][0]{\n  seitentitelMenue, slug\n}": HOME_QUERYResult;
    "*[_type == \"einleitung\"][0]{\n  ueberschrift\n}": EINLEITUNG_QUERYResult;
    "*[_type == \"vision\"][0]{\n  ueberschrift, text\n}": VISION_QUERYResult;
    "*[_type == \"projektbeschreibung\"][0]{\n  ueberschrift,\n  text,\n  grafik{\n    asset->{_id, url},\n    alt\n  },\n  zusatzinfos{\n    grafik{\n      asset->{_id, url},\n      alt\n    },\n    text\n  },\n  teilprojekte{\n    ueberschrift,\n    projekte[]{\n      ueberschrift,\n      text,\n      grafik{\n        asset->{_id, url},\n        alt\n      }\n    }\n  }\n}": PROJEKTBESCHREIBUNG_QUERYResult;
    "*[_type == \"zugangswege\"][0]{\n  ueberschrift,\n  grafik{\n    asset->{\n      _id,\n      url\n    },\n    alt\n  }\n}": ZUGANGSWEGE_QUERYResult;
    "*[_type == \"auswirkungen\"][0]{\n  ueberschrift,\n  grafik{\n    asset->{\n      _id,\n      url\n    },\n    alt\n  }\n}": AUSWIRKUNGEN_QUERYResult;
    "*[_type == \"netzwerkkarte\"][0]{\n  ueberschrift,\n  text,\n  standorte[]{\n    titel,\n    latitude,\n    longitude\n  }\n}": NETZWERKKARTE_QUERYResult;
    "*[_type == \"kontaktSeite\"][0]{\n seitentitelMenue, text, ueberschriftAnsprechpersonen, textAnsprechpersonen\n}": KONTAKT_SEITE_QUERYResult;
    "*[_type == \"impressumSeite\"][0]{\n seitentitelMenue, angabenText, impressumText,\n}": IMPRESSUM_SEITE_QUERYResult;
    "*[_type == \"footer\"][0]{\n  partner,\n  netzwerk,\n  partnerLogos[]{\n    asset->{_id, url},\n    alt,\n    name,\n    url\n  },\n  netzwerkLogos[]{\n    asset->{_id, url},\n    alt,\n    name,\n    url\n  }\n}": FOOTER_QUERYResult;
  }
}
